language: node_js
node_js:
  - '10'
  - '8'
script:
  - npm test
deploy:
  provider: npm
  email: remcohaszing@gmail.com
  api_key: $NPM_ACCESS_TOKEN
  on:
    tags: true
    node: '10'
    repo: remcohaszing/cordova-webpack
